### ISSUE TITLE
steer_drive_rosに引っ張ってくるべきpkg

### ISSUE THREAD

**Issue by AriYu** [CIR-KIT/steer_drive_ros#1]
@MoriKen254 
`third_robot_pkg`から引っ張ってくるpkgを教えてください。

**Comment by MoriKen254** [comment]
@AriYu 

以下の2つです。
- [steer_bot_hardware_gazebo](https://github.com/CIR-KIT/third_robot_pkg/tree/master/steer_bot_hardware_gazebo)
- [third_robot_control/steer_drive_controller](https://github.com/CIR-KIT/third_robot_pkg/tree/master/third_robot_control/steer_drive_controller)

`third_robot_control/steer_drive_controller`が二階層になっていることに特に理由はないので，`steer_drive_controller`の一階層にしてください。

よろしくお願いします。
