### ISSUE TITLE
steer_drive_controllerのインターフェース

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT/steer_drive_ros#11]
下記図のようにするつもりです．いかがでしょうか？賛否問わず，一報頂ければ幸いです．

![steer_drive_controller](https://cloud.githubusercontent.com/assets/12078261/21001880/24e2b35c-bd66-11e6-8f34-e30dcccc73df.png)

steer_drive_controller としては，あくまでcmd_vel を元に，下記joint_interfaceの指令値に変換することにします．

- velocity_joint_interface
  * wheel用に１つ
- position_joint_interface
  * steer用に1つ

robot専用のドライバがこれらの値を受け取り，自身の構成に合わせて指令値を計算し直す，と言うものです．

レビューをよろしくお願いします．

**Comment by forno** [comment]
steer_drive_controller が速度指令 Twist を SteerRobotの一般形(θ, ω)に変換する旨わかりました．
ちょうど良い抽象度で妥当性があると思います．考えた限りでは，同構成のロボットを簡単に挙げられ，それらに十分に適用できると思います．
この構成を支持します．

質問としては，最後の `velocity_joint_interface: ωl, ωr` はRobotHWが処理する際に内部的に生じるデータの一例という認識で良かったでしょうか．
`ωl, ωr` を生成しなくても良い構成というものもありえるかと思います．

**Comment by MoriKen254** [comment]
ありがとうございます．本構成で開発を進めてみます．
もしご意見あれば受け付けますので，もし何かあればよろしくお願いします．

また，

> 質問としては，最後の velocity_joint_interface: ωl, ωr はRobotHWが処理する際に内部的に生じるデータの一例という認識で良かったでしょうか．
> ωl, ωr を生成しなくても良い構成というものもありえるかと思います．

との件は，おっしゃる通りです．ここでは一例として挙げました．確認ありがとうございます．

**Comment by forno** [comment]
お疲れ様です。
すでに対応したプルリクが順次マージされていますが、落ち着いて考える時間がようやく取れ、インターフェース改善案を思いついたので共有までにコメントさせて頂きます。

一般的なコントローラーの仕様に思いを馳せたところ、JointCommandInterface という概念が存在することを思い出しました。
すなわち、1コントローラにつき、1ジョイント(可動部)という仕組みが一般的であるとおもいます。
現在の案のコントローラインターフェースは2ジョイントを有しているため、他コントローラと連携が取れず、また、特別な使い方を覚えなければRobotHWに適用できないものであると思います。

そこで、それぞれの可動部を分離し、操舵部に位置制御コントローラー、推進部に速度制御コントローラーを作成して適用すれば、同様の効果が得られ、その他コントローラと同様の扱いが取れると考えました。

デメリットとしては、単に別種のコントローラ2台になるので、同時に使うことを想定している旨表示しなければならないことと、別種であるため、コントローラ内で複雑な連携を行うことが難しくなることなどが考えられます。

メリットは、既存のJointCommandInterfaceと同様の構成となることで、使い方が特別にならないこと、他のコントローラに容易に差し替えられること、RobotHWが複数のコントローラに対応する際に特別な対応がいらないこと、*操舵部を容易に速度制御に変えられること*、などが考えられます。

ご意見お待ちしております。

**Comment by MoriKen254** [comment]
コメントありがとうございます．

おっしゃる通りで，JointCommandInterfeceがros_controllerの基本形です．

その中でも，diff_drive_controller だけが例外的に，1コントローラ内に複数のjointsを持つ構成を取っており，steer_drive_controller はこれを踏襲しています．コントローラ内での速度制御やオドメトリの解釈がしやすいというメリットが有り，意図的に踏襲していると言う経緯があります．

独立二輪を使用しているロボットではdiff_drive_controllerがデファクトスタンダードとなっていると思うので，同構成を踏襲することはそんなに悪い話ではないと思っていました．

> それぞれの可動部を分離し、操舵部に位置制御コントローラー、推進部に速度制御コントローラーを作成して適用すれば、同様の効果が得られ、その他コントローラと同様の扱いが取れると考えました。

の構成に合わせたコントローラを作成するというのも良い案だと思います．RobotHW側に負担を欠けてしまう点は確かに面倒臭いです…．そんなことをするくらいなら，普通に組んだほうが良いというのも合理的な案だと思います．

もし同構成でやりたい意志があれば，現行の steer_drive_controlelr とは別立てで作成してみていただけけないでしょうか？

現在目標としている12/25までに，今からスクラッチでソフトウェア構成を変更し，システムレベル対応させ直すというリソースの確保まで想定していなかったため，そのリソースを現状の小生からはひねり出せそうにありません…．小生の力不足で，大変申し訳ございません．

**Comment by forno** [comment]
@MoriKen254 

ご一考いただき誠にありがとうございます。
私の方は diff_drive_controller の仕様を詳しく知らなかったので、それを踏襲した構成にした旨わかりました。
また、デメリットでも挙げた通り、オドメトリなどと連携した複雑な処理は難しい問題だと思いますので、このままの構成で進める判断を支持します。

また暇が取れた時にdiff_drive_controllerの仕様を確認しておきます。
そのときに今回提案した構成が有用か再度自分の中で判断します。

また、それはこちらでも12/25に間に合いません。
私の方こそ力及ばず申し訳ございません。

**Comment by AriYu** [comment]
このままの仕様で始めたいと思います。

**Comment by forno** [comment]
@MoriKen254 

diff_drive_controller の仕様をきちんと確認しました。
私の勘違いや思い違いなどにより、interfaceとコントローラの関係を誤って認識していることがわかりました。
特に、InterfaceとControllerをやや混同していた節がありました。

diff_drive_controller でも、RobotHW は一般的なJointCommandInterfaceを利用した構成を取れていました。
また、これからコントローラが複数のジョイントを保有してコントロールしてもRobotHWが特殊な構造をとらなくてよいこともわかりました。

今回は私の勘違いや思い違いにより、混乱させてしまったことお詫び申し上げます。

このままの構成が最も良いと思います。

**Comment by MoriKen254** [comment]
@forno 

いえいえ，こちらこそ指摘していただいて，最もな意見だなーと感じていました．RobotHWがごちゃごちゃするのは事実です．もっとシンプルに設定できる可能性があるかもしれない，ということですからね．

両方作ってみて使いやすい方を取る，というのが理想的とは思うのですが，現状のスケジュールだと難しそうだなぁという印象です．

使いやすさの改善という点は，ひとまず今の構成で動かしてみて，RobotHW or RobotHWSim 側で抽象化できる部分があれば，それをサンプルテンプレートとして提供するのが，１つの打開案でしょうね．

刺激になるご意見，ありがとうございます．

@AriYu さん，対応のほどよろしくおねがいします．

**Comment by MoriKen254** [comment]
ひとまず閉リンク対応していないURDFの仕様においては、この方針で突っ走ってみます。

本家プルリク側でなにか指摘を受けたら修正します。
