### ISSUE TITLE
Compile issue with steer_drive_controller::SteerDriveController and steer_bot_hardware_gazebo.cpp

### ISSUE THREAD

**Issue by benwarrick** [CIR-KIT/steer_drive_ros#21]
Hello. I've run into two issues trying to compile the kinetic-devel version of steer_drive_ros. For steer_drive_controller::SteerDriveController it complains that it is an invalid new-expresssion of abstract class type. It points to line 48 on steer_drive_controller.cpp

Also for steer_bot_hardware_gazebo I see 

class gazebo::physics::Joint’ has no member named ‘SetAngle’
         sim_joints_[i]->SetAngle(0, pos_cmd);

Am I compiling this project wrong or is this a known issue? 

Thanks!

**Comment by RyodoTanaka** [comment]
I think, it depends on Gazebo version...
How do you think @MoriKen254 ??

**Comment by MoriKen254** [comment]
Thanks for asking us the question.

> it depends on Gazebo version..

Exactly.

> trying to compile the kinetic-devel version of steer_drive_ros

Did you surely set the branch `kinetic-devel`?

We use `SetPosition` instead in the `kinetic-devel` branch.
- https://github.com/CIR-KIT/steer_drive_ros/blob/kinetic-devel/steer_bot_hardware_gazebo/src/steer_bot_hardware_gazebo.cpp#L215

Maybe your local branch is still either `master` or `indigo-devel` if you still see the setAngle error.
- https://github.com/CIR-KIT/steer_drive_ros/blob/master/steer_bot_hardware_gazebo/src/steer_bot_hardware_gazebo.cpp#L237
- https://github.com/CIR-KIT/steer_drive_ros/blob/indigo-devel/steer_bot_hardware_gazebo/src/steer_bot_hardware_gazebo.cpp#L237

I believe the abstract class problem will also be solved when you switch the branch to `kinetic-devel`

**Comment by benwarrick** [comment]
Yes, you're exactly right. I didn't use git correctly and had instead the master. Thanks!
