### ISSUE TITLE
Is there a working example in Gazebo? 

### ISSUE THREAD

**Issue by benwarrick** [CIR-KIT/steer_drive_ros#22]
I see in the controller test folder the launch file view_steerbot.launch, but it does not use the steer drive controller. I also followed the documentation to cirkit, and have tried several of their launch files. Most aren't working, but cirkit_unit03_world_old.launch runs without error, but there are no Twist topics, so i guess that means the controller isn't running. I don't know. This is hard to figure out without something working and without documentation. 

I'm using the devel kinetic versions. Thanks.

**Comment by MoriKen254** [comment]
@benwarrick 
Sorry for late reply.

Our CIRKIT-UNIT03 is the one.

http://wiki.ros.org/Robots/CIR-KIT-Unit03

If you use kinetic, please switch the branch of [this repo](https://github.com/CIR-KIT/steer_drive_ros) and [cirkit_unit03_pkgs](https://github.com/CIR-KIT-Unit03/cirkit_unit03_pkgs/tree/kinetic-devel) to kinetic-devel.

It should work as being seen in the video [here](https://github.com/ros-controls/ros_controllers/pull/289).

Thanks in advance!
