### ISSUE TITLE
test run

### ISSUE THREAD

**Issue by kossumov** [CIR-KIT/steer_drive_ros#27]
Hi guys,
I'm kinda new to ROS
I want to test steer_drive_ros and don't know how.
I noticed from README (https://github.com/CIR-KIT/steer_drive_ros/blob/kinetic-devel/steer_drive_controller/README.md)
that there is a test robot "third_robot". (maybe I'm wrong cause README is in japanese, and I translated it using google translate)

What I've done so far:
1. clone the steer_drive_controller from github repository into my catkinized workspace
2. built it (catkin_make)
3. source path.bash
4. roslaunch third_robot_gazebo third_robot_world.launch 

So here I get an error that third_robot_gazebo doesn't exist.

Am I doing this right?
Thanks

**Comment by MoriKen254** [comment]
Please refer to the following link. The robot uses steer_drive_controller.

http://wiki.ros.org/Robots/CIR-KIT-Unit03

After install related packages, try the command as follows.

```bash
roslaunch cirkit_unit03_autorun autorun_gazebo.launch
```

This should work like the next video.

[![steer_drive_controller_kinetic_demo](https://i.ytimg.com/vi/O2TjvZomuYY/hqdefault.jpg)](https://youtu.be/O2TjvZomuYY)

**Comment by kossumov** [comment]
alright, thanks
