### ISSUE TITLE
Melodic Release

### ISSUE THREAD

**Issue by akouri-dd** [CIR-KIT/steer_drive_ros#30]
Is this deprecated? 

What would it take to use this package with melodic?

**Comment by callen5914** [comment]
Same... Would love to know...

**Comment by tomlogan501** [comment]
Wait until #31 
I hope it will be merged, otherwise there is a lot of forks

**Comment by MoriKen254** [comment]
created https://github.com/CIR-KIT/steer_drive_ros/tree/melodic-devel

sorry for late response
