### ISSUE TITLE
steer_drive_controller のPull requestを本家に出すか

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT/steer_drive_ros#4]
ROS使いの皆さんならご存知かもしれませんが，`steer_drive_controller`の公開について色々心配があったので，先日`ros-japan-users`に相談したところ，`yoneken`が回答を下さいました．

## yoneken の結論: 本家にPull-request 出そー！

ということです^^

やるならやるで皆さんの協力が欲しいです．
この辺の方向性も結論を出したいので，一回ミーティングでお話させて下さい．

### 当初の私の懸念事項
下記の事情があり，どのように公開すればよいのか心配になった．

- 本家の`diff_drive_controller`をかなり参考にしている
- そもそもOSSに本格的に乗っかるのが初めてで勝手が分からない

### yoneken の回答

あまりビビらず積極的に本家にコミットすべしとのこと．根拠は下記の通り．

> - APTで提供されているパッケージに取込んでもらえれば，rosdepでインストールできるようになって嬉しい
> - 自分のリポジトリをAPTのパッケージ化するやり方がわからない
> - 本家のパッケージのほうが，他人の目に止まりやすく，使ってもらいやすい（かも）
> - 自分が永続的にパッケージのメンテナになって，ROSのバージョンが増えるたびに環境を作ってビルドをチェックしたり，リリースを切ったりするのがめんどくさい（一番大きな理由）

### これに対する私の見解
- 正論であり合理的．
- 実際`steer_drive_controller`の需要はあるだろうし，当たって砕けろで本家にコミットしてみる経験も良かろうと思う．
- 協力者の皆さんが「ROS本家にコミットしたことあります」と言えるようになるのが素敵．

### さらに湧いてきた懸念事項
- それなりに綺麗にしないといけない．
  - コーディングスタイル，ソフトウェア構成等全体的に．
  - 基本は`diff_drive_controller`に従えばよいだろうが．
- 実はこのコントローラ，Gazeboと連携するのは一癖あり，特別な`RobotHWSim`が必要となる．こいつの位置づけをどうするか？
  - urdf が閉リンク対応していないので，前輪のリンク機構を再現するためにちょっとズルをしないといけない．
  - 実はここがややこしいので，一回ちゃんと整理したいと思っていた．

**Comment by RyodoTanaka** [comment]
@MoriKen254 
私も本家にリクエストを出すことに賛成です！
まずはビルドテスト環境（コードテスト含む）を構築した後、コードの修正を行うほうが採用してもらいやすくなると思います．

よろしくお願いしますm(_ _)m

**Comment by MoriKen254** [comment]
steer_drive_controller のインターフェースから見直す必要があるので，テストも合わせて直します．少し時間を頂ければと思います．

**Comment by MoriKen254** [comment]
ようやく本家にプルリク出せました。なんか、競合もいるみたいです…。もっと早く出せてたらよかったのですがね汗。

どうなることやら。

https://github.com/ros-controls/ros_controllers/pull/289

**Comment by AriYu** [comment]
@Moriken254
おお、本当に素晴らしいです。

**Comment by MoriKen254** [comment]
プルリクの件，~~ややこしい~~面白いことになってきました笑．

とりあえず彼らに判断を委ねてみたのではありますが，良かったら知恵を貸してください．

**Comment by MoriKen254** [comment]
`steer_drive_controller` 改め、`ackermann_steering_controller`が`ros_controllers`に正式にマージされました。

- Pull Request
  - https://github.com/ros-controls/ros_controllers/pull/356

- Repository just after merged
  - https://github.com/ros-controls/ros_controllers/tree/kinetic-devel
  - ![image](https://user-images.githubusercontent.com/12078261/48312088-f1687f00-e5ec-11e8-9adc-5ac01ee9666a.png)

改良等は本家に移行、`steer_drive_controller`は`deprecated`とし、以降はbug fixのみとする予定です。

表題の目標は達成されたので、Issueを閉じます。

皆さん、ありがとうございました！
