### ISSUE TITLE
コードテストについて

### ISSUE THREAD

**Issue by RyodoTanaka** [CIR-KIT/steer_drive_ros#8]
#7 で問題提起していますが、コードテストを実行する必要があります．
私はこれまでにコードテストをやったことがないので、勉強時間が必要で少し時間を要します．
また、具体的にどんなテストにするのかを共有したいです。
よろしくお願いします．

**Comment by forno** [comment]
Google Test (以下gtest)は[現在使っている](https://github.com/forno/libics3)ので多少であれば力になれるかもしれません。

gtestのイメージがつかない場合のためにふんわりとした説明をすると、`cassert` を強力にしたようなものです。c++でコーディングします。

テストに関してですが、controllerとmove_baseのプラグインのテスト方法が調べても分からなかったため、これを除いたテストを考えた場合、gtest を用いて定義された関数やオブジェクトを呼び出して戻り値や例外のテストする、いわゆる単体テストの他には思いつきませんでした。
とはいえ、現在外部から呼び出せるように関数が定義されているところは稀で、プラグイン内に処理が埋め込まれてしまっているため、呼び出してテストすることも困難な状況です。

リファクタして、処理の大部分を別オブジェクトに移してプラグイン部分で処理しないようにすれば、オブジェクトに対してテストがかけれるため、不変条件のチェックや、値を時間で与えたときの反応などのテストを行えるようになるかと思います。

他にも案など有りましたらご提案ください。

また、各種プラグイン生成後のテスト方法についてわかることがあれば教えて頂けると幸いです。それらはgtestではテストできません。

なお、controllerのプラグインについて、単に立ち上がるかどうかであれば `spawner` で呼び出すlaunchを書くという案も考えられます。

**Comment by MoriKen254** [comment]
本件について，third_robot_pkg 側にブランチを作っていたのを失念していました．普通に作成途中ですが．．

https://github.com/CIR-KIT/third_robot_pkg/tree/add_test_for_steer_drive_controller/third_robot_control/steer_drive_controller/test

元ネタはdiff_drive_controllerのテストコードです．

直進指令与えてたときにオドメトリがそれっぽい値になっているかとか，JointInterfaceの現在値にNaNが入ってもオドメトリはNaNにならないかとか，パラメータサーバをわざと空にした時にデフォルト設定で処理してくれるかとか，そんな感じのやつです．

**Comment by forno** [comment]
とても良さげなテストコードですね。テストについてどこがどう影響しているのか教わりたいです。

さて、後出しで申し訳ないのですが、私はテストはなるべくコードがあるリポジトリに含めたいと思うので、実行時依存が複雑過ぎないのであればテストをこちらに持ってきたいなと思いました。
おそらく実行時依存の関係でそちらに送ったものだったと記憶しているので、そうであれば翻すのは混乱を生むと思うので、ひとまずそのまま作業を進めて、後ほどでよいのでテストをこちらに戻せないか再考できればと思います。

**Comment by MoriKen254** [comment]
ご無沙汰しております。事情により、大分反応が遅れてしまいまして、すみません。

ひとまず、https://github.com/CIR-KIT/steer_drive_ros/pull/9 にてテストコード自体はこのリポジトリに組み込んでいます。

ひとまずリマインドの意味も込めて、テストの影響を記しておきます。

## 共通ファイル
- ディレクトリ
  - [steer_drive_controller/test/common](https://github.com/CIR-KIT/steer_drive_ros/tree/kinetic-devel/steer_drive_controller/test/common)
- 概要
  - 下記ファイルを格納
    - controller を動作させるためのRobotHWやテスト用クラスの実体
    - controllerや同実体を実行するためのlaunchファイルや、可視化用のRvizファイル
  - 上記ファイルは個別のテストから呼び出される

## 個別のテスト関連ファイル
- ディレクトリ
  - [steer_drive_controller/test](https://github.com/CIR-KIT/steer_drive_ros/tree/kinetic-devel/steer_drive_controller/test) 以下のcommon以外のディレクトリ
- 概要
  - 下記ファイルを格納
    - テストコードの実体
    - テストコード実行時の設定用yamlファイル
    - テストコード実行用のlaunchファイル
  - 上記ファイルよりcommonのファイルを呼び出す

これ以降は、本家のプルリク側で議論した後に、修正が必要な部分は直すかもしれません。

落ち着いたら本Issueは閉じます。

よろしくおねがいします。

**Comment by MoriKen254** [comment]
テストコードつきでPRがマージされました。

本件 Close します。。
